"""Les variables `QUANT_*` déclarées — DONNÉES seulement (lues par `reglages`).

Une ligne par variable : (nom, type, défaut, rôle[, critique[, choix[, secret]]]).
Ajouter une variable au code sans l'ajouter ici fait échouer
`tests/common/test_reglages.py`.
"""

DECLAREES = (
    # --- Exécution, taille, risque (critiques) -----------------------------------
    ("QUANT_CADENCE_JOURS", "int", "5", "séances entre deux rebalancements", True),
    ("QUANT_DD_TARGET", "float", "0.25", "drawdown visé du satellite", True),
    ("QUANT_CORE_SPEC", "str", "qqq:0.5", "cœur indiciel (symbole:poids,…)", True),
    ("QUANT_MIN_POSITION", "float", None, "plancher d'une ligne ($)", True),
    ("QUANT_ATTENTE_FILLS_S", "float", None, "attente max des fills (s)", True),
    ("QUANT_IGNORE_SESSION", "drapeau", None, "envoie hors séance (tests)", True),
    ("QUANT_DISJONCTEUR", "bool", None, "disjoncteur de passage armé", True),
    ("QUANT_DISJONCTEUR_SEUIL", "float", None, "seuil du disjoncteur", True),
    ("QUANT_KILL_DD", "float", "0.30", "kill-switch drawdown (backtest)", True),
    ("QUANT_INTRADAY_DD", "float", None, "kill-switch DD intraday (négatif)", True),
    ("QUANT_RISK_MAX_WEIGHT", "float", None, "poids max d'une ligne", True),
    ("QUANT_RISK_MAX_WEIGHT_BASKET", "float", None, "poids max ligne panier", True),
    ("QUANT_RISK_MAX_POSITIONS", "int", None, "nombre max de lignes", True),
    ("QUANT_RISK_MAX_ORDER_PCT", "float", None, "ordre max (part du compte)", True),
    ("QUANT_RISK_MAX_GROSS", "float", None, "exposition brute max", True),
    ("QUANT_RISK_OVERLAY", "drapeau", None, "overlay de risque (opt-in)", True),
    ("QUANT_CRYPTO_PCT", "float", None, "part max du compte en crypto", True),
    ("QUANT_CRYPTO_VENUE", "choix", "binance", "place crypto", True,
       ("binance", "bitmart")),
    ("QUANT_NO_CRYPTO_LIVE", "bool", "1", "pas d'ordre crypto réel", True),
    ("QUANT_BINANCE_TESTNET", "bool", "1", "Binance en bac à sable", True),
    ("QUANT_BROKER_EQUITY", "str", "alpaca", "courtier actions", True),
    ("QUANT_BROKER_CRYPTO", "str", None, "courtier crypto", True),
    ("QUANT_IBKR_ENABLE", "drapeau", None, "active IBKR", True),
    ("QUANT_REBAL_MULTI", "drapeau", None, "rebalancement multi-comptes", True),
    ("QUANT_QUALITY_SELECTION", "bool", None, "sélection par qualité", True),
    ("QUANT_REGIME_INDICE", "str", None, "indice exogène du régime (QQQ, SPY)", True),
    ("QUANT_SWING_PAPER", "bool", None, "sleeve swing paper", True),
    ("QUANT_SWING_MAX_NAMES", "int", "5", "lignes max du swing", True),
    ("QUANT_SWING_NAV_PCT", "float", "0", "part du compte du swing", True),
    ("QUANT_EARNINGS", "drapeau", None, "blackout résultats", True),
    ("QUANT_FEES", "bool", "1", "frais appliqués (backtest)", True),
    # --- Données, univers, calcul --------------------------------------------------
    ("QUANT_PRICE_DB", "chemin", None, "base de prix"),
    ("QUANT_MACRO_DB", "chemin", "data/macro.db", "base macro"),
    ("QUANT_JOURNAL_DB", "chemin", None, "journal de trades"),
    ("QUANT_SOCIAL_DB", "chemin", None, "base sociale"),
    ("QUANT_MKTCAP_FILE", "chemin", None, "capitalisations"),
    ("QUANT_CACHE_DIR", "chemin", ".cache/crypto", "cache crypto"),
    ("QUANT_MODELS_DIR", "chemin", None, "registre des modèles"),
    ("QUANT_VAULT", "chemin", None, "vault Obsidian"),
    ("QUANT_X_JSONL", "chemin", None, "export X"),
    ("QUANT_SORTIE", "chemin", None, "sortie d'un travail (posée par le code)"),
    ("QUANT_UNIVERSE", "str", None, "univers personnalisé"),
    ("QUANT_HISTORY_DAYS", "int", "4015", "profondeur d'historique (jours)"),
    ("QUANT_FUND", "choix", None, "fondamentaux", False, ("", "synthetic", "real")),
    ("QUANT_FUND_MAX", "int", "1200", "fondamentaux : titres max"),
    ("QUANT_FUND_WORKERS", "int", "6", "fondamentaux : parallélisme"),
    ("QUANT_ALLOW_SYNTHETIC", "drapeau", None, "autorise le synthétique"),
    ("QUANT_AUDIT", "choix", "warn", "audit des prix", False, ("warn", "1", "strict")),
    ("QUANT_COV_DISK_CACHE", "bool", "1", "cache disque des covariances"),
    ("QUANT_COV_SHRINK", "bool", "1", "shrinkage des covariances"),
    ("QUANT_COV_TTL_DAYS", "int", None, "TTL du cache de covariance"),
    ("QUANT_STAGE_CACHE", "bool", "1", "cache des étapes"),
    ("QUANT_MEGACAP_TOP", "int", "10", "taille du panier mégacaps"),
    ("QUANT_DEVICE", "choix", None, "matériel forcé", False,
     ("", "cpu", "mps", "cuda")),
    ("QUANT_MATERIEL", "str", None, "matériel déclaré (manifeste)"),
    ("QUANT_SEED", "int", "7", "graine des entraînements"),
    ("QUANT_EXPERIMENT", "str", "EXP-AUTO", "identifiant d'expérience"),
    ("QUANT_HTTP_RETRIES", "int", "3", "tentatives HTTP"),
    ("QUANT_HTTP_BACKOFF", "float", "1.5", "recul HTTP"),
    ("QUANT_VERBOSE_YF", "drapeau", None, "yfinance bavard"),
    ("QUANT_CRYPTO", "drapeau", None, "active la crypto (ingestion)"),
    ("QUANT_NEWS", "drapeau", None, "actualités dans l'analyse"),
    ("QUANT_HF_JOURNAL", "str", None, "dataset HuggingFace du journal"),
    # --- Passages programmés, site, API --------------------------------------------
    ("QUANT_CRYPTO_HEURE_UTC", "int", None, "heure UTC du passage crypto"),
    ("QUANT_LIVE_AVANT_CLOTURE", "int", None, "minutes avant la clôture"),
    ("QUANT_LIVE_HOUR", "int", None, "heure du cron live (shell)"),
    ("QUANT_LIVE_MIN", "int", None, "minute du cron live (shell)"),
    ("QUANT_IGNORER_FENETRE", "drapeau", None, "ignore la fenêtre (shell)"),
    ("QUANT_LIVE_LITE", "drapeau", None, "snapshot allégé pour le live"),
    ("QUANT_LIVE_LITE_SKIP_FUNDAMENTALS", "drapeau", None, "live sans fondamentaux"),
    ("QUANT_REPORT_LITE", "drapeau", None, "rapports allégés"),
    ("QUANT_MAX_REPORTS", "int", "120", "rapports max"),
    ("QUANT_NO_LLM", "drapeau", None, "aucun appel LLM"),
    ("QUANT_LOCAL_LLM", "str", "gemma3n:e4b", "modèle LLM local"),
    ("QUANT_EMBED", "choix", "tfidf", "recherche du vault", False, ("tfidf", "ollama")),
    ("QUANT_EMBED_MODEL", "str", "nomic-embed-text", "modèle d'embedding"),
    ("QUANT_CORS_ORIGINS", "liste", None, "origines CORS de l'API"),
    ("QUANT_WEBHOOK_TOKEN", "str", None, "jeton du webhook", False, (), True),
    ("QUANT_API_PORT", "int", None, "port de l'API (shell)"),
    ("QUANT_WEB_PORT", "int", None, "port du front (shell)"),
    ("QUANT_BIND_HOST", "str", None, "hôte d'écoute (shell)"),
    ("QUANT_BRANCH", "str", None, "branche suivie par make start (shell)"),
    ("QUANT_NO_UPDATE", "drapeau", None, "make start sans mise à jour (shell)"),
    ("QUANT_REFRESH", "str", None, "rafraîchissement (shell)"),
    ("QUANT_PREDMKT", "str", None, "marchés prédictifs (shell)"),
    ("QUANT_VERROU_FORCE", "str", None, "force la régénération du verrou"),
    ("QUANT_IBKR_HOST", "str", None, "hôte IBKR"),
    ("QUANT_IBKR_PORT", "int", None, "port IBKR"),
    # --- Sources sociales ------------------------------------------------------------
    ("QUANT_X_RSS", "liste", None, "flux RSS X"),
    ("QUANT_TG_CANAUX", "liste", None, "canaux Telegram"),
    ("QUANT_DISCORD_SALONS", "liste", None, "salons Discord"),
    ("QUANT_SOCIAL_GARDER", "int", "50", "publications gardées"),
    ("QUANT_RSSHUB_ENV", "str", None, "RSSHub (shell)"),
    ("QUANT_RSSHUB_PORT", "int", None, "port RSSHub (shell)"),
)
